###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysqlserver:
        image: 'mysql:8.0'
        working_dir: /application
        container_name: mysqlserver
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
            - MYSQL_USER=username
            - MYSQL_PASSWORD=password
        ports:
            - '13002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '13000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysqlserver
        environment:
            PMA_HOST: mysqlserver
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8181:80
#    phpmyadmin:
#        image: phpmyadmin/docker-phpmyadmin
#        links:
#            - mysqlserver
#        ports:
#            - 8181:80
#        environment:
#            PMA_HOST: mysqlserver
#            PMA_PORT: 3306
#            PMA_ARBITRARY: 1
#            MYSQL_SERVER: mysqlserver
#            MYSQL_HOST: mysqlserver
#            MYSQL_USERNAME: root
#            MYSQL_ROOT_PASSWORD: password
